=== gcube-team/gcube-releases/vre-management/resourcebroker-serialization-servicearchive/1.2.0-4.6.0-126929/xsd/changelog.xsd
<?xml version="1.0" encoding="UTF-8"?>
	<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
               elementFormDefault="qualified" attributeFormDefault="unqualified">
               
        <xs:annotation>
                <xs:documentation xml:lang="en">
                XML Schema for gCube changelog.xml file Version 1.0 Last modified: 13/07/2010 
                </xs:documentation>
        </xs:annotation>
	       
	    <xs:element name="ReleaseNotes" type="ReleaseNotesType" />
	    <xs:complexType name="ReleaseNotesType">
	         	<xs:sequence>
	               <xs:element name="Changeset" type="ChangesetType" minOccurs="1" maxOccurs="unbounded"/>       
	           </xs:sequence>                  
     	</xs:complexType>
     	
     	<xs:complexType name="ChangesetType">
        	 <xs:sequence>
            	 <xs:element name="Change" type="xs:string"  minOccurs="1" maxOccurs="unbounded"/>       
         	</xs:sequence>
         	<xs:attribute name="component" type="xs:string"/>
         	<xs:attribute name="date" type="xs:date"/>                   
  		</xs:complexType>
     		          
</xs:schema>

=== gcube-team/gcube-releases/portlets-admin/resource-management-portlet/6.4.0-4.11.0-150651/changelog.xml
<ReleaseNotes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xsd/changelog.xsd">
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.6-3-0"
		date="2017-02-24">
		<Change>Changed codes for AuthZ framework</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.6-0-0"
		date="2016-06-28">
		<Change>Ported to Liferay 6.2</Change>
		<Change>Removed Software Upload Widget</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.5-7-0"
		date="2015-11-24">
		<Change>Added support for new AuthZ framework, Feature #1496</Change>
		<Change>Removed Activation Record Widget, #1497</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.5-6-0"
		date="2015-09-28">
		<Change>Refactored code in dependencies to promote reuse of sweeper
			features</Change>
		<Change>Implemented Feature #187, remove scope operation with Report
		</Change>
		<Change>Implemented Feature #446 Show SmartGearsDistribution version
			instead of SmartGearsDistributionBundle version for Distro Version
		</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.5-5-0"
		date="2015-06-09">
		<Change>Fix for Incident #187, remove scope operation not passing
			through Resource Manager
		</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.5-4-0"
		date="2015-04-21">
		<Change>fixed Ticket #1119 Resource Management / Monitor wrong generic
			resource query
		</Change>
		<Change>Ported to GWT 270</Change>
		<Change>Updated for showing SmartGears versions in gHN Grid View
		</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.5-3-0"
		date="2014-12-09">
		<Change>Added Host column in grid view for service endpoints</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.5-2-0"
		date="2014-06-06">
		<Change>Ported to gCore Free Portal</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.5-1-0"
		date="2013-10-21">
		<Change>New Look And Feel</Change>
		<Change>Ported to GWT 2-5-1</Change>
		<Change>Ported to Feather Weight Stack</Change>
		<Change>Removed GCF Dependency</Change>
		<Change>Logging with sl4j Enabled</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.4-1-0"
		date="2013-04-19">
		<Change>added activation record widget as external module</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.4-0-0"
		date="2013-02-27">
		<Change>Mavenized</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.3-0-0"
		date="2013-01-13">
		<Change>Reengineered completely to support modules</Change>
		<Change>Added one click feature for retrieving resource profiles
		</Change>
		<Change>generic Resource grid view show description</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.2-3-0"
		date="2012-10-18">
		<Change>Added plugin for TreeManager activation record creation
		</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.2-2-0"
		date="2012-09-21">
		<Change>New Software Upload Wizard integrated</Change>
		<Change>Added support for resource manger service 2</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.2-0-0"
		date="2012-05-04">
		<Change>Completely restyled pinned resources panel (former opened
			resources panel) using CSS3 and HTML5
		</Change>
		<Change>Added support for runtime resources editing</Change>
		<Change>Added support for remove from scope</Change>
		<Change>Added automatic show of gHN List at startup with possibility
			to set it on or off by editing a configuration file
		</Change>
		<Change>Added automatic highlighting of low memory or disk machines
			and gHN States
		</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.1-0-0"
		date="2010-10-15">
		<Change>First release on gxt and gwt2.0</Change>
		<Change>for etics 2.0.1 release</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.1-1-0"
		date="2010-10-24">
		<Change>for etics 2.1.0 release</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.1-2-0"
		date="2010-11-3">
		<Change>for etics 2.2.0 release</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.1-3-0"
		date="2010-11-24">
		<Change>for etics 2.2.1 release</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.1-4-0"
		date="2011-01-13">
		<Change>for etics 2.2.2 release</Change>
		<Change>Added sweeper for invalid resources (expired GHNs and orphan
			RIs)
		</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.1-7-0"
		date="2011-07-01">
		<Change>Correctly lists GCUBECollection type from new Content Manager
		</Change>
		<Change>Correctly lists VIEW type from new Content Manager</Change>
		<Change>Ported to GWT 2.2 GXT 2.2.3</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.resource-management-portlet.1-9-0"
		date="2011-12-14">
		<Change>Added support for runtime resources</Change>
	</Changeset>
	<Changeset
		component="org.gcube.portlets-admin.resource-management-portlet.1-10-0"
		date="2012-02-17">
		<Change>Added support for runtime resources removal</Change>
		<Change>Added support for runtime resources scope change</Change>
	</Changeset>
</ReleaseNotes>

=== gcube-team/gcube-releases/spatial-data/geonetwork/3.0.0-4.0.0-130716/distro/changelog.xml
<ReleaseNotes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xsd/changelog.xsd">
	<Changeset component="geonetwork.1-0-0" date="2013-03-01">
		<Change>First Release</Change>
	</Changeset>
	<Changeset  component="geonetwork.2-1-1" date="2015-05-25">
		<Change>Integration fixes</Change>
	</Changeset>
	<Changeset  component="geonetwork.3-0-0" date="2016-06-25">
		<Change>Added interface GeoNetworkAdministration</Change>
		<Change>User and group management facilities</Change>
		<Change>Gcube 4 SDI automatic configuration</Change>
		<Change>Improved check on configuration constraints</Change>
	</Changeset>
</ReleaseNotes>

=== gcube-team/gcube-releases/portlets-admin/rmp-common-library/2.8.2-4.15.0-178536/changelog.xml
<ReleaseNotes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xsd/changelog.xsd">
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.2-8-2"
		date="2019-03-11">
		<Change>Task #12037, Please provide a way to get the Context UUID in ContextManager</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.2-8-1"
		date="2018-10-14">
		<Change>Feature #12726 update resource at vo level rather than vre level</Change>
		<Change>Feature #11788 ContextManager class added</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.2-7-1"
		date="2017-02-24">
		<Change>Changed codes for AuthZ framework</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.2-6-0"
		date="2015-11-24">
		<Change>Added support for new AuthZ framework, Feature #1496</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.2-5-0"
		date="2015-09-28">
		<Change>Refactored code to promote reuse of sweeper features</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.2-4-0"
		date="2015-08-04">
		<Change>Implemented Feature #187, remove scope operation with Report</Change>
		<Change>Implemented Feature #446 Show SmartGearsDistribution version instead of SmartGearsDistributionBundle version for Distro Version</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.2-3-0"
		date="2015-06-09">
		<Change>Fix for Incident #187, remove scope operation not passing
			through Resource Manager</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.2-2-1"
		date="2014-05-25">
		<Change>Fix for Incident #148, Resource Sweeper does not sweep GHN
			Resources
		</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.2-2-0"
		date="2014-12-09">
		<Change>Modified xqueries for showing SmartGears and SmarGearsBundle
			version
		</Change>
		<Change>Updated label names for the gHN grid columns</Change>
		<Change>Modified xquery to fix bug about wrong scoped generic resource
		</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.2-1-0"
		date="2014-12-09">
		<Change>Modified xquery to get also the hostname info about service
			endpoints in a given scope
		</Change>
		<Change>Modified the Resource detail model class to in shared package
			to support the change explained above
		</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.2-0-0"
		date="2013-10-21">
		<Change>Ported to Feather Weight Stack</Change>
		<Change>Removed GCF Dependency</Change>
		<Change>Logging with sl4j Enabled</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.1-2-0"
		date="2013-04-19">
		<Change>Create valid request for TM-plugins</Change>
	</Changeset>
	<Changeset component="org.gcube.portlets-admin.rmp-common-library.1-0-0"
		date="2010-10-15">
		<Change>First release</Change>
	</Changeset>
</ReleaseNotes>
